nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmScopes:
  buf:
    npmRegistryServer: "https://buf.build/gen/npm/v1"

# Resolves some peer dependency issues from buf-generated libraries
packageExtensions:
  "@buf/lekkodev_sdk.connectrpc_es@*":
    dependencies:
      "@bufbuild/protobuf": "^1.7.2"
